<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="login.without_sucess.test"
    errors="0" failures="1" hostname="" id="" package="login" skipped="1"
    tests="3" time="22.86" timestamp="">
  
    <testcase name="Wrong password" classname="login.without_sucess.test" time="18.79" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="Wrong e-mail" classname="login.without_sucess.test" time="1.993" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="E-mail blank" classname="login.without_sucess.test" time="2.073" assertions="3">

    

      <failure message="Testing if element &lt;Element [name=@alertInfo]&gt; contains text: &#34;Opps. Cadê o email!&#34; in 1000 ms. - expected [0;32m&#34;Opps. Cadê o email!&#34;[0m but got: [0;31m&#34;Opps. Cadê o email?&#34;[0m">    at Page.expectAlertInfo (/home/wlf/Desktop/Sync/curso-node-zombie/qaninja/zombieplus/pages/login.js:18:21)
    at Object.E-mail blank (/home/wlf/Desktop/Sync/curso-node-zombie/qaninja/zombieplus/tests/login/without_sucess.test.js:24:14)</failure>

    <failure message="    at Page.expectAlertInfo (/home/wlf/Desktop/Sync/curso-node-zombie/qaninja/zombieplus/pages/login.js:18:21)">    at Object.E-mail blank (/home/wlf/Desktop/Sync/curso-node-zombie/qaninja/zombieplus/tests/login/without_sucess.test.js:24:14)</failure>
    </testcase>
  

  

  
    
    <testcase
      name="Password blank" classname="login.without_sucess.test">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
